#!/usr/bin/env python
#The line above is important so that this file is interpreted with Python when running it.

# Import of python modules.
import math # use of pi.

# import of relevant libraries.
import rospy # module for ROS APIs
from geometry_msgs.msg import Twist # message type for cmd_vel
from sensor_msgs.msg import LaserScan # message type for scan
from nav_msgs.msg import Odometry # message for odometry (robot position)
from tf.transformations import euler_from_quaternion

from simple_flocking.simple_motion import SimpleMotion

# Constants.
FREQUENCY = 10 #Hz.
LINEAR_VELOCITY = 0.15 # m/s
ANGULAR_VELOCITY = math.pi/4 # rad/s
LASER_ANGLE_FRONT = 0 # radians
MIN_THRESHOLD_DISTANCE = 0.6 # m, threshold distance.
DEFAULT_CMD_VEL_TOPIC = 'cmd_vel'
DEFAULT_SCAN_TOPIC = 'scan'
DEFAULT_LOCAL_ODOM_TOPIC = 'odom'

"""Main function."""
def main():
    # 1st. initialization of node.
    rospy.init_node("simple_exploration")

    # Sleep for a few seconds to wait for the registration.
    rospy.sleep(2)

    # Initialization of the class for the simple motion.
    simple_exploration = SimpleMotion()

    # If interrupted, send a stop command.
    rospy.on_shutdown(simple_exploration.stop)

    # Robot moves 1 m forward, rotate of 180 degrees, and moves 1 m forward.
    try:
        while not rospy.is_shutdown():
            rate = rospy.Rate(FREQUENCY)
            simple_exploration.rotate_in_place(math.pi/4)
            simple_exploration.move_forward(5)
            rate.sleep()
    except rospy.ROSInterruptException:
        rospy.logerr("ROS node interrupted.")


if __name__ == "__main__":
    """Run the main function."""
    main()
