#!/usr/bin/env python
#The line above is important so that this file is interpreted with Python when running it.

import rospy
from geometry_msgs.msg import Twist # message type for cmd_vel


class TestRotator:
    def __init__(self):
        self._cmd_pub = rospy.Publisher("cmd_vel", Twist, queue_size=1)

    def rotate(self):
        while not rospy.is_shutdown():
            twist_msg = Twist()
            twist_msg.angular.z = 0.2
            self._cmd_pub.publish(twist_msg)


def main():
    """Main function."""

    # 1st. initialization of node.
    rospy.init_node("test_rotator")

    # Sleep for a few seconds to wait for the registration.
    rospy.sleep(2)

    rot = TestRotator()
    rot.rotate()


if __name__ == "__main__":
    """Run the main function."""
    main()
